---
title: "2014-2018: Weekly vs Monthly"
author: "Pritam Dalal"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load_packages, include=FALSE}
library(tidyverse)
```

```{r, reading_monthly_data, include=FALSE, cache=TRUE}
chr_csv_file_names <-
        list.files(
            "data_output/monthly"
            , full.names = TRUE
            , pattern = ".*_pnl_master.csv*"
        )

lst_monthly <- list()
for (ix in 1:length(chr_csv_file_names)){
    lst_monthly[[length(lst_monthly) + 1]] <- 
        read_csv(chr_csv_file_names[ix], col_types = cols())
}

df_monthly <- bind_rows(lst_monthly)
df_monthly <-
    df_monthly %>% mutate(tenor = "monthly")
```



```{r, reading_weekly_data, include=FALSE, cache=TRUE}
chr_csv_file_names <-
        list.files(
            "data_output/weekly"
            , full.names = TRUE
            , pattern = ".*_pnl_master.csv*"
        )

lst_weekly <- list()
for (ix in 1:length(chr_csv_file_names)){
    lst_weekly[[length(lst_weekly) + 1]] <- 
        read_csv(chr_csv_file_names[ix], col_types = cols())
}

df_weekly <- bind_rows(lst_weekly)

df_weekly <- 
    df_weekly %>% mutate(tenor = "weekly")
```




```{r, combinind_monthly_weekly_pnls, include=FALSE, cache=TRUE}
df_pnl <- bind_rows(df_monthly, df_weekly)
```




```{r, daily_ttd_pnl, include=FALSE, cache=TRUE}
df_pnl_daily <- 
    df_pnl %>% 
        group_by(tenor, underlying_symbol, variation, data_date) %>% 
        summarize(
            naked = sum(dly_opt_pnl)
            , dh = sum(dly_tot_pnl)
        ) %>% 
        mutate(
            ttd_naked = cumsum(naked)
            , ttd_dh = cumsum(dh)
        )
```


```{r, calc_sharpe, include=FALSE, cache=TRUE}
df_sharpe <- 
    df_pnl_daily %>% 
        group_by(tenor, underlying_symbol, variation) %>% 
        summarize(
            avg_naked = mean(naked)
            , avg_dh = mean(dh)
            , sd_naked = sd(naked)
            , sd_dh = sd(dh)
            , sharpe_naked = (mean(naked) / sd(naked)) * sqrt(252)
            , sharpe_dh = (mean(dh) / sd(dh)) * sqrt(252)
            
        )
```




## Delta-Hedged


```{r}
# restricting myself only to situations with where sharpe is positive
# for both
# 16 of 19 have higher Sharpes
df_sharpe %>% filter(tenor == "monthly") %>% 
    left_join(
        df_sharpe %>% filter(tenor=="weekly")
        , by = c("underlying_symbol", "variation")
        , suffix = c("_monthly", "_weekly")
    ) %>% 
    filter(avg_dh_weekly > 0) %>% 
    filter(avg_dh_monthly > 0) %>% 
    filter(sharpe_dh_weekly > sharpe_dh_monthly)

```



```{r, graphing_dh, cache=TRUE, fig.width=6, fig.height=25}
df_sharpe %>% 
    ggplot(aes(x = tenor, y = sharpe_dh, fill=tenor)) +
    geom_bar(stat = "identity", position = "dodge")  +
    geom_text(aes(label=round(sharpe_dh, 2), vjust=-0.25)) + 
    facet_grid(underlying_symbol~factor(variation)) +
    ylim(-1, 3) +
    labs(
        title = "Sharpe-Ratio by Delta (Delta-Hedge)"
        , subtitle = "Monthy vs Weekly"
        , x = "delta"
        , y = "sharpe-ratio"
    )
```


## Naked
```{r}
# restricting myself only to situations with where sharpe is positive
# for both
# 9 of 19 have higher Sharpes for weeklys
df_sharpe %>% filter(tenor == "monthly") %>% 
    left_join(
        df_sharpe %>% filter(tenor=="weekly")
        , by = c("underlying_symbol", "variation")
        , suffix = c("_monthly", "_weekly")
    ) %>% 
    filter(avg_naked_weekly > 0) %>% 
    filter(avg_naked_monthly > 0) %>% 
    filter(sharpe_naked_weekly > sharpe_naked_monthly)

```


```{r, graphing_naked, cache=TRUE, fig.width=6, fig.height=25}
df_sharpe %>% 
    ggplot(aes(x = tenor, y = sharpe_naked, fill=tenor)) +
    geom_bar(stat = "identity", position = "dodge")  +
    geom_text(aes(label=round(sharpe_naked, 2), vjust=-0.25)) + 
    facet_grid(underlying_symbol~factor(variation)) +
    ylim(-1, 3) +
    labs(
        title = "Sharpe-Ratio by Delta (Naked)"
        , subtitle = "Monthy vs Weekly"
        , x = "delta"
        , y = "sharpe-ratio"
    )
```






















