---
title: "Optimal Unwind: Weekly vs Monthly"
author: "Pritam Dalal"
date: "3/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
```

```{r}
df_underlying <- 
    tibble(
        symbol = c("DIA", "EEM", "EWZ", "FXI" ,"GDX", "GLD"
                       , "IWM", "QQQ", "SLV", "SPY", "USO","XLE")
    )

df_pnl_weekly <- tibble()
df_pnl_monthly <- tibble()
for (ix in 1:nrow(df_underlying)){
    
    chr_underlying <- df_underlying$symbol[ix]
    
    # weekly
    chr_path <- 
    paste0(
        "data_output/weekly/"
        , str_to_lower(chr_underlying)
        , "_weekly_2014_2018_managed_pnl.csv"
    )
    df_pnl_weekly <-
        df_pnl_weekly %>% 
        bind_rows(
            read_csv(chr_path, col_types = cols()) %>% 
            mutate(underlying = chr_underlying)
        )
    
    # monthly
    chr_path <- 
    paste0(
        "data_output/monthly/"
        , str_to_lower(chr_underlying)
        , "_monthly_2014_2018_managed_pnl.csv"
    )
    df_pnl_monthly <-
        df_pnl_monthly %>% 
        bind_rows(
            read_csv(chr_path, col_types = cols()) %>% 
            mutate(underlying = chr_underlying)
        )    
}
```




```{r}
# df_pnl_weekly <- 
#     read_csv("data_output/weekly/dia_weekly_2014_2018_managed_pnl.csv")
# 
# df_pnl_monthly <- 
#     read_csv("data_output/monthly/dia_monthly_2014_2018_managed_pnl.csv")
# 

```



```{r}
# calculating sharpe for "unmanaged" delta-hedge strategy
# all underlyings combined
df_pnl_weekly %>% 
    filter(loss_trigger == 1000) %>% 
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>% 
    filter(dh_threshold == 0) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    )


# calculating sharpe for "unmanaged" naked strategy
# all underlyings combined
df_pnl_weekly %>% 
    filter(loss_trigger == 1000) %>% 
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>% 
    filter(dh_threshold == 1) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    )


df_pnl_weekly %>% 
    filter(loss_trigger == 1000) %>% 
    View()
```

```{r}
df_breach_count <- 
    df_pnl_weekly %>% 
        group_by(underlying, dh_threshold, loss_trigger, expiration) %>% 
        summarize(
            breach = sum(any(breach)) 
        ) %>% 
        group_by(dh_threshold, loss_trigger) %>% 
        summarize(
            breach_count = sum(breach)
        )
   

df_pnl_weekly %>% distinct(loss_trigger) %>% View()
```


```{r}
df_pnl_weekly %>% 
    filter(loss_trigger != 1000) %>% 
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>% 
    filter(dh_threshold == 0) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    ) %>%
    ggplot() + 
        geom_point(aes(x=loss_trigger, y=sharpe)) +
        labs(
            title = "weekly: delta-hedge"
        )



df_pnl_monthly %>% 
    filter(loss_trigger != 1000) %>%
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>% 
    filter(dh_threshold == 0) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    ) %>% 
    ggplot() + 
        geom_point(aes(x=loss_trigger, y=sharpe)) +
        labs(
            title = "monthly: delta-hedge"
        )
```







```{r}
df_pnl_weekly %>% 
    filter(loss_trigger != 1000) %>%
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>% 
    filter(dh_threshold == 1) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    ) %>% 
    ggplot() + 
        geom_point(aes(x=loss_trigger, y=sharpe)) + 
        labs(
            title = "weekly: naked"
        )




df_pnl_monthly %>%
    filter(loss_trigger != 1000) %>%
    filter(strategy == "strangle") %>% 
    filter(variation == 0.1) %>%        
    filter(dh_threshold == 1) %>% 
    group_by(loss_trigger, data_date) %>% 
    summarize(
        dh_pnl = sum(scaled_managed_pnl)
    ) %>% 
    group_by(loss_trigger) %>% 
    summarize(
        avg_pnl = mean(dh_pnl)
        , sd_pnl = sd(dh_pnl)
        , sharpe = (mean(dh_pnl) / sd(dh_pnl)) * sqrt(252)
    ) %>%
    ggplot() + 
        geom_point(aes(x = loss_trigger, y = sharpe)) +
        labs(
            title = "monthly: naked"
        )
```





